from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 512)
        MainWindow.setMinimumSize(QtCore.QSize(683, 512))
        MainWindow.setMaximumSize(QtCore.QSize(683, 512))
        MainWindow.setBaseSize(QtCore.QSize(1366, 1024))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.pages.setGeometry(QtCore.QRect(0, 0, 681, 511))
        self.pages.setStyleSheet("#pages {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.pages.setObjectName("pages")
        self.connect_page = QtWidgets.QWidget()
        self.connect_page.setObjectName("connect_page")
        self.connectLabel = QtWidgets.QLabel(self.connect_page)
        self.connectLabel.setGeometry(QtCore.QRect(110, 26, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.connectLabel.setFont(font)
        self.connectLabel.setObjectName("connectLabel")
        self.start_bg = QtWidgets.QLabel(self.connect_page)
        self.start_bg.setGeometry(QtCore.QRect(460, 90, 121, 51))
        self.start_bg.setText("")
        self.start_bg.setPixmap(QtGui.QPixmap("assets/Start-connection-btn.png"))
        self.start_bg.setScaledContents(True)
        self.start_bg.setObjectName("start_bg")
        self.connectCard = QtWidgets.QLabel(self.connect_page)
        self.connectCard.setGeometry(QtCore.QRect(110, 70, 220, 89))
        self.connectCard.setMinimumSize(QtCore.QSize(220, 89))
        self.connectCard.setMaximumSize(QtCore.QSize(220, 89))
        self.connectCard.setText("")
        self.connectCard.setTextFormat(QtCore.Qt.PlainText)
        self.connectCard.setPixmap(QtGui.QPixmap("assets/Connect-card.png"))
        self.connectCard.setScaledContents(True)
        self.connectCard.setObjectName("connectCard")
        self.codeInput = QtWidgets.QTextEdit(self.connect_page)
        self.codeInput.setGeometry(QtCore.QRect(150, 100, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.codeInput.sizePolicy().hasHeightForWidth())
        self.codeInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.codeInput.setFont(font)
        self.codeInput.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.codeInput.setAutoFillBackground(False)
        self.codeInput.setStyleSheet("#codeInput { background: transparent !important}")
        self.codeInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.codeInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.codeInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.codeInput.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.codeInput.setTabStopWidth(4)
        self.codeInput.setAcceptRichText(False)
        self.codeInput.setObjectName("codeInput")
        self.startNetworkLabel = QtWidgets.QLabel(self.connect_page)
        self.startNetworkLabel.setGeometry(QtCore.QRect(410, 30, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.startNetworkLabel.setFont(font)
        self.startNetworkLabel.setObjectName("startNetworkLabel")
        self.startNetworkBtn = QtWidgets.QPushButton(self.connect_page)
        self.startNetworkBtn.setGeometry(QtCore.QRect(460, 90, 121, 51))
        self.startNetworkBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startNetworkBtn.setStyleSheet("#connectBtn,\n"
"#startNetworkBtn {\n"
"    border-radius: 10;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.startNetworkBtn.setText("")
        self.startNetworkBtn.setCheckable(False)
        self.startNetworkBtn.setChecked(False)
        self.startNetworkBtn.setAutoDefault(False)
        self.startNetworkBtn.setDefault(False)
        self.startNetworkBtn.setFlat(True)
        self.startNetworkBtn.setObjectName("startNetworkBtn")
        self.startNetworkCard = QtWidgets.QLabel(self.connect_page)
        self.startNetworkCard.setGeometry(QtCore.QRect(410, 70, 220, 89))
        self.startNetworkCard.setMinimumSize(QtCore.QSize(220, 89))
        self.startNetworkCard.setMaximumSize(QtCore.QSize(220, 89))
        self.startNetworkCard.setText("")
        self.startNetworkCard.setTextFormat(QtCore.Qt.PlainText)
        self.startNetworkCard.setPixmap(QtGui.QPixmap("assets/start-network-card.png"))
        self.startNetworkCard.setScaledContents(True)
        self.startNetworkCard.setObjectName("startNetworkCard")
        self.bg = QtWidgets.QLabel(self.connect_page)
        self.bg.setGeometry(QtCore.QRect(0, 0, 681, 511))
        self.bg.setMaximumSize(QtCore.QSize(1366, 16777215))
        self.bg.setAutoFillBackground(False)
        self.bg.setLineWidth(0)
        self.bg.setText("")
        self.bg.setTextFormat(QtCore.Qt.PlainText)
        self.bg.setPixmap(QtGui.QPixmap("assets/Bg.png"))
        self.bg.setScaledContents(True)
        self.bg.setWordWrap(False)
        self.bg.setObjectName("bg")
        self.connectBtn = QtWidgets.QPushButton(self.connect_page)
        self.connectBtn.setGeometry(QtCore.QRect(270, 100, 31, 31))
        self.connectBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.connectBtn.setStyleSheet("#startNetworkBtn {\n"
"    border-radius: 10;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.connectBtn.setText("")
        self.connectBtn.setCheckable(False)
        self.connectBtn.setChecked(False)
        self.connectBtn.setAutoDefault(False)
        self.connectBtn.setDefault(False)
        self.connectBtn.setFlat(True)
        self.connectBtn.setObjectName("connectBtn")
        self.connectBtn.clicked.connect(lambda: self.pages.setCurrentIndex(self.pages.currentIndex() + 1))
        self.bg.raise_()
        self.connectLabel.raise_()
        self.connectCard.raise_()
        self.codeInput.raise_()
        self.startNetworkLabel.raise_()
        self.startNetworkCard.raise_()
        self.start_bg.raise_()
        self.connectBtn.raise_()
        self.startNetworkBtn.raise_()
        self.pages.addWidget(self.connect_page)
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.bg_2 = QtWidgets.QLabel(self.home_page)
        self.bg_2.setGeometry(QtCore.QRect(0, 0, 681, 511))
        self.bg_2.setMaximumSize(QtCore.QSize(1366, 16777215))
        self.bg_2.setAutoFillBackground(False)
        self.bg_2.setLineWidth(0)
        self.bg_2.setText("")
        self.bg_2.setTextFormat(QtCore.Qt.PlainText)
        self.bg_2.setPixmap(QtGui.QPixmap("assets/Bg.png"))
        self.bg_2.setScaledContents(True)
        self.bg_2.setWordWrap(False)
        self.bg_2.setObjectName("bg_2")
        self.stopBg = QtWidgets.QLabel(self.home_page)
        self.stopBg.setGeometry(QtCore.QRect(110, 70, 215, 88))
        self.stopBg.setMinimumSize(QtCore.QSize(215, 88))
        self.stopBg.setMaximumSize(QtCore.QSize(215, 88))
        self.stopBg.setText("")
        self.stopBg.setPixmap(QtGui.QPixmap("assets/stop-bg.png"))
        self.stopBg.setScaledContents(True)
        self.stopBg.setObjectName("stopBg")
        self.networkInfoLabel = QtWidgets.QLabel(self.home_page)
        self.networkInfoLabel.setGeometry(QtCore.QRect(110, 30, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.networkInfoLabel.setFont(font)
        self.networkInfoLabel.setObjectName("networkInfoLabel")
        self.stopBtn = QtWidgets.QPushButton(self.home_page)
        self.stopBtn.setGeometry(QtCore.QRect(160, 90, 111, 41))
        self.stopBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopBtn.setStyleSheet("#connectBtn {\n"
"    border-radius: 10;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"#startNetworkBtn {\n"
"    border-radius: 10;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.stopBtn.setText("")
        self.stopBtn.setCheckable(False)
        self.stopBtn.setChecked(False)
        self.stopBtn.setAutoDefault(False)
        self.stopBtn.setDefault(False)
        self.stopBtn.setFlat(True)
        self.stopBtn.setObjectName("stopBtn")
        self.stopBtn.clicked.connect(lambda: self.pages.setCurrentIndex(self.pages.currentIndex() - 1))
        self.qrCode = QtWidgets.QLabel(self.home_page)
        self.qrCode.setGeometry(QtCore.QRect(420, 100, 181, 171))
        self.qrCode.setStyleSheet("#qrCode {border-radius:100px;}")
        self.qrCode.setText("")
        self.qrCode.setPixmap(QtGui.QPixmap("assets/qr-code.png"))
        self.qrCode.setScaledContents(True)
        self.qrCode.setObjectName("qrCode")
        self.outputCode = QtWidgets.QLabel(self.home_page)
        self.outputCode.setGeometry(QtCore.QRect(450, 310, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.outputCode.setFont(font)
        self.outputCode.setAlignment(QtCore.Qt.AlignCenter)
        self.outputCode.setObjectName("outputCode")
        self.stopBg_2 = QtWidgets.QLabel(self.home_page)
        self.stopBg_2.setGeometry(QtCore.QRect(380, 70, 258, 312))
        self.stopBg_2.setMinimumSize(QtCore.QSize(258, 312))
        self.stopBg_2.setMaximumSize(QtCore.QSize(258, 312))
        self.stopBg_2.setText("")
        self.stopBg_2.setPixmap(QtGui.QPixmap("assets/qr-bg.png"))
        self.stopBg_2.setScaledContents(True)
        self.stopBg_2.setObjectName("stopBg_2")
        self.networkInfoLabel_2 = QtWidgets.QLabel(self.home_page)
        self.networkInfoLabel_2.setGeometry(QtCore.QRect(380, 30, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.networkInfoLabel_2.setFont(font)
        self.networkInfoLabel_2.setObjectName("networkInfoLabel_2")
        self.bg_2.raise_()
        self.stopBg.raise_()
        self.networkInfoLabel.raise_()
        self.stopBtn.raise_()
        self.stopBg_2.raise_()
        self.networkInfoLabel_2.raise_()
        self.qrCode.raise_()
        self.outputCode.raise_()
        self.pages.addWidget(self.home_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ventus"))
        self.connectLabel.setText(_translate("MainWindow", "Connect"))
        self.codeInput.setPlaceholderText(_translate("MainWindow", "Enter code"))
        self.startNetworkLabel.setText(_translate("MainWindow", "Start a network"))
        self.networkInfoLabel.setText(_translate("MainWindow", "Connection"))
        self.outputCode.setText(_translate("MainWindow", "abc - defg - hij"))
        self.networkInfoLabel_2.setText(_translate("MainWindow", "Network"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
