[package]
name = "async-ftp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.2"
futures = "^0.3.31"
tokio =  {version = "^1.40.0", features = ["full", "net"] }
tokio-util = { version = "^0.7.12", features = ["full", "codec"] }
