# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import file_sync_pb2 as file__sync__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in file_sync_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileSyncServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSync = channel.unary_unary(
                '/FileSyncService/StartSync',
                request_serializer=file__sync__pb2.ClientRequest.SerializeToString,
                response_deserializer=file__sync__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.SyncComplete = channel.unary_unary(
                '/FileSyncService/SyncComplete',
                request_serializer=file__sync__pb2.ClientRequest.SerializeToString,
                response_deserializer=file__sync__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.NotifySync = channel.unary_unary(
                '/FileSyncService/NotifySync',
                request_serializer=file__sync__pb2.Notification.SerializeToString,
                response_deserializer=file__sync__pb2.SyncResponse.FromString,
                _registered_method=True)


class FileSyncServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifySync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileSyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSync': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSync,
                    request_deserializer=file__sync__pb2.ClientRequest.FromString,
                    response_serializer=file__sync__pb2.SyncResponse.SerializeToString,
            ),
            'SyncComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncComplete,
                    request_deserializer=file__sync__pb2.ClientRequest.FromString,
                    response_serializer=file__sync__pb2.SyncResponse.SerializeToString,
            ),
            'NotifySync': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifySync,
                    request_deserializer=file__sync__pb2.Notification.FromString,
                    response_serializer=file__sync__pb2.SyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileSyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FileSyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileSyncService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSyncService/StartSync',
            file__sync__pb2.ClientRequest.SerializeToString,
            file__sync__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSyncService/SyncComplete',
            file__sync__pb2.ClientRequest.SerializeToString,
            file__sync__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifySync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSyncService/NotifySync',
            file__sync__pb2.Notification.SerializeToString,
            file__sync__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
