# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_sync.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'file_sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66ile_sync.proto\"\"\n\rClientRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"9\n\x0cNotification\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x18\n\x10origin_client_id\x18\x02 \x01(\t\"\x1e\n\x0cSyncResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x98\x01\n\x0f\x46ileSyncService\x12*\n\tStartSync\x12\x0e.ClientRequest\x1a\r.SyncResponse\x12-\n\x0cSyncComplete\x12\x0e.ClientRequest\x1a\r.SyncResponse\x12*\n\nNotifySync\x12\r.Notification\x1a\r.SyncResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTREQUEST']._serialized_start=19
  _globals['_CLIENTREQUEST']._serialized_end=53
  _globals['_NOTIFICATION']._serialized_start=55
  _globals['_NOTIFICATION']._serialized_end=112
  _globals['_SYNCRESPONSE']._serialized_start=114
  _globals['_SYNCRESPONSE']._serialized_end=144
  _globals['_FILESYNCSERVICE']._serialized_start=147
  _globals['_FILESYNCSERVICE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
